const calcData = [
    {
        name:'one',
        value:1,
        display:'1',
        classes:['calcbutton','numberButton']
    },
    {
        name:'two',
        value:2,
        display:'2',
        classes:['calcbutton','numberButton']
    },
    {
        name:'three',
        value:3,
        display:'3',
        classes:['calcbutton','numberButton']
    },
    {
        name:'four',
        value:4,
        display:'4',
        classes:['calcbutton','numberButton']
    },
    {
        name:'five',
        value:5,
        display:'5',
        classes:['calcbutton','numberButton']
    },
    {
        name:'six',
        value:6,
        display:'six',
        classes:['calcbutton','numberButton']
    },
    {
        name:'seven',
        value:7,
        display:'7',
        classes:['calcbutton','numberButton']
    },
    {
        name:'eight',
        value:8,
        display:'8',
        classes:['calcbutton','numberButton']
    },
    {
        name:'nine',
        value:9,
        display:'9',
        classes:['calcbutton','numberButton']
    },
    {
        name:'zero',
        value:0,
        display:'0',
        classes:['calcbutton','numberButton']
    },
    {
        name:'add',
        value:'add',
        display:'+',
        classes:['calcbutton','operation']
    },
    {
        name:'subtract',
        value:'subtract',
        display:'-',
        classes:['calcbutton','operation']
    },
    {
        name:'multiply',
        value:'multiply',
        display:'×',//alt +0215
        classes:['calcbutton','operation']
    },
    {
        name:'divide',
        value:'divide',
        display:'÷',//alt+0247
        classes:['calcbutton','operation']
    },
    {
        name:'equals',
        value:'equals',
        display:'=',
        classes:['calcbutton']
    },
    {
        name:'',
        value:'',
        display:'',
        classes:['calcbutton']
    },
    {
        name:'',
        value:'',
        display:'',
        classes:['calcbutton']
    },
    {
        name:'',
        value:'',
        display:'',
        classes:['calcbutton']
    }
]

export default calcData